export interface EmojiEntry {
  char: string;
  keywords: string[];
}

export interface EmojiCategory {
  id: string;
  label: string;
  icon: string;
  emojis: EmojiEntry[];
}

export const EMOJI_CATEGORIES: EmojiCategory[] = [
  {
    id: 'smileys',
    label: 'Smileys & Emotion',
    icon: '😀',
    emojis: [
      { char: '😀', keywords: ['grinning', 'smile', 'happy', 'cười'] },
      { char: '😃', keywords: ['smiley', 'happy', 'joy'] },
      { char: '😄', keywords: ['smile', 'happy', 'laugh'] },
      { char: '😁', keywords: ['grin', 'smile', 'teeth'] },
      { char: '😆', keywords: ['laughing', 'lol', 'haha'] },
      { char: '😅', keywords: ['sweat smile', 'relief', 'phew'] },
      { char: '🤣', keywords: ['rofl', 'rolling', 'funny', 'lol'] },
      { char: '😂', keywords: ['joy', 'tears', 'laugh', 'lol', 'cười ra nước mắt'] },
      { char: '🙂', keywords: ['slight smile', 'happy'] },
      { char: '🙃', keywords: ['upside down', 'silly'] },
      { char: '😉', keywords: ['wink', 'flirt'] },
      { char: '😊', keywords: ['blush', 'smile', 'happy', 'shy'] },
      { char: '😇', keywords: ['angel', 'halo', 'innocent'] },
      { char: '🥰', keywords: ['love', 'hearts', 'adore'] },
      { char: '😍', keywords: ['heart eyes', 'love', 'crush'] },
      { char: '🤩', keywords: ['star struck', 'excited', 'wow'] },
      { char: '😘', keywords: ['kiss', 'love', 'hôn'] },
      { char: '😗', keywords: ['kiss'] },
      { char: '😚', keywords: ['kiss', 'closed eyes'] },
      { char: '😙', keywords: ['kiss', 'smile'] },
      { char: '🥲', keywords: ['smiling tear', 'bittersweet'] },
      { char: '😋', keywords: ['yum', 'delicious', 'tongue'] },
      { char: '😛', keywords: ['tongue', 'playful'] },
      { char: '😜', keywords: ['wink tongue', 'silly'] },
      { char: '🤪', keywords: ['zany', 'crazy', 'wild'] },
      { char: '😝', keywords: ['tongue', 'squint'] },
      { char: '🤑', keywords: ['money mouth', 'rich'] },
      { char: '🤗', keywords: ['hug', 'ôm'] },
      { char: '🤭', keywords: ['giggle', 'oops', 'hand over mouth'] },
      { char: '🫢', keywords: ['gasp', 'shock'] },
      { char: '🫣', keywords: ['peek', 'shy'] },
      { char: '🤫', keywords: ['shush', 'quiet', 'secret'] },
      { char: '🤔', keywords: ['thinking', 'hmm', 'suy nghĩ'] },
      { char: '🫡', keywords: ['salute', 'respect'] },
      { char: '🤐', keywords: ['zip mouth', 'silence'] },
      { char: '🤨', keywords: ['raised eyebrow', 'suspicious'] },
      { char: '😐', keywords: ['neutral', 'meh'] },
      { char: '😑', keywords: ['expressionless', 'blank'] },
      { char: '😶', keywords: ['no mouth', 'speechless'] },
      { char: '🫠', keywords: ['melting', 'awkward'] },
      { char: '😏', keywords: ['smirk', 'sly'] },
      { char: '😒', keywords: ['unamused', 'annoyed'] },
      { char: '🙄', keywords: ['eye roll', 'whatever'] },
      { char: '😬', keywords: ['grimace', 'awkward', 'yikes'] },
      { char: '😮‍💨', keywords: ['exhale', 'sigh'] },
      { char: '🤥', keywords: ['lying', 'pinocchio'] },
      { char: '😌', keywords: ['relieved', 'content'] },
      { char: '😔', keywords: ['pensive', 'sad'] },
      { char: '😪', keywords: ['sleepy', 'tired'] },
      { char: '🤤', keywords: ['drooling'] },
      { char: '😴', keywords: ['sleeping', 'zzz', 'ngủ'] },
      { char: '😷', keywords: ['mask', 'sick'] },
      { char: '🤒', keywords: ['thermometer', 'sick', 'fever'] },
      { char: '🤕', keywords: ['injured', 'bandage', 'hurt'] },
      { char: '🤢', keywords: ['nauseated', 'sick', 'gross'] },
      { char: '🤮', keywords: ['vomit', 'sick'] },
      { char: '🤧', keywords: ['sneeze'] },
      { char: '🥵', keywords: ['hot', 'sweating'] },
      { char: '🥶', keywords: ['cold', 'freezing'] },
      { char: '🥴', keywords: ['woozy', 'dizzy', 'drunk'] },
      { char: '😵', keywords: ['dizzy', 'knocked out'] },
      { char: '😵‍💫', keywords: ['dizzy', 'spiral'] },
      { char: '🤯', keywords: ['mind blown', 'shocked'] },
      { char: '🤠', keywords: ['cowboy', 'hat'] },
      { char: '🥳', keywords: ['party', 'celebrate', 'birthday'] },
      { char: '🥸', keywords: ['disguise', 'glasses'] },
      { char: '😎', keywords: ['cool', 'sunglasses'] },
      { char: '🤓', keywords: ['nerd', 'geek'] },
      { char: '🧐', keywords: ['monocle', 'curious'] },
      { char: '😕', keywords: ['confused'] },
      { char: '🫤', keywords: ['diagonal mouth', 'meh'] },
      { char: '😟', keywords: ['worried'] },
      { char: '🙁', keywords: ['frown', 'sad'] },
      { char: '☹️', keywords: ['frown', 'sad'] },
      { char: '😮', keywords: ['open mouth', 'surprised', 'wow'] },
      { char: '😯', keywords: ['hushed', 'surprised'] },
      { char: '😲', keywords: ['astonished', 'shocked'] },
      { char: '😳', keywords: ['flushed', 'embarrassed'] },
      { char: '🥺', keywords: ['pleading', 'puppy eyes'] },
      { char: '🥹', keywords: ['holding back tears'] },
      { char: '😦', keywords: ['frowning', 'open mouth'] },
      { char: '😧', keywords: ['anguished'] },
      { char: '😨', keywords: ['fearful', 'scared'] },
      { char: '😰', keywords: ['anxious', 'sweat'] },
      { char: '😥', keywords: ['sad', 'disappointed'] },
      { char: '😢', keywords: ['cry', 'sad', 'khóc'] },
      { char: '😭', keywords: ['sob', 'cry loudly', 'khóc to'] },
      { char: '😱', keywords: ['scream', 'shocked', 'fear'] },
      { char: '😖', keywords: ['confounded'] },
      { char: '😣', keywords: ['persevere', 'struggle'] },
      { char: '😞', keywords: ['disappointed'] },
      { char: '😓', keywords: ['downcast', 'sweat'] },
      { char: '😩', keywords: ['weary', 'tired'] },
      { char: '😫', keywords: ['tired', 'exhausted'] },
      { char: '🥱', keywords: ['yawn', 'bored', 'tired'] },
      { char: '😤', keywords: ['triumph', 'huff', 'proud'] },
      { char: '😡', keywords: ['angry', 'mad', 'giận'] },
      { char: '😠', keywords: ['angry', 'annoyed'] },
      { char: '🤬', keywords: ['cursing', 'swearing', 'furious'] },
      { char: '😈', keywords: ['devil', 'evil'] },
      { char: '👿', keywords: ['angry devil'] },
      { char: '💀', keywords: ['skull', 'dead'] },
      { char: '☠️', keywords: ['skull crossbones', 'danger'] },
    ],
  },
  {
    id: 'people',
    label: 'People & Body',
    icon: '👋',
    emojis: [
      { char: '👋', keywords: ['wave', 'hello', 'bye', 'chào'] },
      { char: '🤚', keywords: ['raised hand'] },
      { char: '🖐️', keywords: ['hand', 'stop'] },
      { char: '✋', keywords: ['hand', 'stop', 'high five'] },
      { char: '🖖', keywords: ['vulcan', 'spock'] },
      { char: '👌', keywords: ['ok', 'perfect'] },
      { char: '🤌', keywords: ['pinched fingers', 'italian'] },
      { char: '🤏', keywords: ['pinch', 'small'] },
      { char: '✌️', keywords: ['peace', 'victory'] },
      { char: '🤞', keywords: ['crossed fingers', 'luck'] },
      { char: '🫰', keywords: ['heart hand', 'finger heart'] },
      { char: '🤟', keywords: ['love you', 'rock'] },
      { char: '🤘', keywords: ['rock on', 'metal'] },
      { char: '🤙', keywords: ['call me', 'shaka'] },
      { char: '👈', keywords: ['point left'] },
      { char: '👉', keywords: ['point right'] },
      { char: '👆', keywords: ['point up'] },
      { char: '🖕', keywords: ['middle finger'] },
      { char: '👇', keywords: ['point down'] },
      { char: '☝️', keywords: ['point up', 'one'] },
      { char: '👍', keywords: ['thumbs up', 'like', 'good', 'ok', 'tốt'] },
      { char: '👎', keywords: ['thumbs down', 'dislike', 'bad'] },
      { char: '✊', keywords: ['fist', 'power'] },
      { char: '👊', keywords: ['punch', 'fist bump'] },
      { char: '🤛', keywords: ['left fist'] },
      { char: '🤜', keywords: ['right fist'] },
      { char: '👏', keywords: ['clap', 'applause', 'vỗ tay'] },
      { char: '🙌', keywords: ['raise hands', 'celebrate', 'praise'] },
      { char: '🫶', keywords: ['heart hands', 'love'] },
      { char: '👐', keywords: ['open hands'] },
      { char: '🤲', keywords: ['palms up', 'pray'] },
      { char: '🤝', keywords: ['handshake', 'deal'] },
      { char: '🙏', keywords: ['pray', 'thanks', 'please', 'cảm ơn'] },
      { char: '✍️', keywords: ['writing'] },
      { char: '💅', keywords: ['nail polish', 'sassy'] },
      { char: '🤳', keywords: ['selfie'] },
      { char: '💪', keywords: ['muscle', 'strong', 'flex'] },
      { char: '🦾', keywords: ['mechanical arm'] },
      { char: '👂', keywords: ['ear'] },
      { char: '👃', keywords: ['nose'] },
      { char: '🧠', keywords: ['brain', 'smart'] },
      { char: '🦷', keywords: ['tooth'] },
      { char: '👀', keywords: ['eyes', 'look', 'watching'] },
      { char: '👁️', keywords: ['eye'] },
      { char: '👅', keywords: ['tongue'] },
      { char: '👄', keywords: ['mouth', 'lips'] },
      { char: '💋', keywords: ['kiss mark', 'lips'] },
      { char: '🩸', keywords: ['blood'] },
      { char: '👶', keywords: ['baby'] },
      { char: '🧒', keywords: ['child'] },
      { char: '👦', keywords: ['boy'] },
      { char: '👧', keywords: ['girl'] },
      { char: '🧑', keywords: ['person'] },
      { char: '👨', keywords: ['man'] },
      { char: '👩', keywords: ['woman'] },
      { char: '🧓', keywords: ['older person'] },
      { char: '👴', keywords: ['old man'] },
      { char: '👵', keywords: ['old woman'] },
      { char: '🙍', keywords: ['frowning person'] },
      { char: '🙎', keywords: ['pouting person'] },
      { char: '🙅', keywords: ['no gesture'] },
      { char: '🙆', keywords: ['ok gesture'] },
      { char: '💁', keywords: ['information desk'] },
      { char: '🙋', keywords: ['raising hand'] },
      { char: '🧏', keywords: ['deaf person'] },
      { char: '🙇', keywords: ['bowing person'] },
      { char: '🤦', keywords: ['facepalm'] },
      { char: '🤷', keywords: ['shrug', 'idk'] },
      { char: '👮', keywords: ['police'] },
      { char: '🕵️', keywords: ['detective', 'spy'] },
      { char: '💂', keywords: ['guard'] },
      { char: '🥷', keywords: ['ninja'] },
      { char: '👷', keywords: ['construction worker'] },
      { char: '🫅', keywords: ['royalty'] },
      { char: '🤴', keywords: ['prince'] },
      { char: '👸', keywords: ['princess'] },
      { char: '👳', keywords: ['turban'] },
      { char: '👲', keywords: ['cap'] },
      { char: '🧕', keywords: ['headscarf'] },
      { char: '🤵', keywords: ['tuxedo', 'groom'] },
      { char: '👰', keywords: ['bride', 'veil'] },
      { char: '🤰', keywords: ['pregnant'] },
      { char: '🤱', keywords: ['breastfeeding'] },
      { char: '👼', keywords: ['angel baby'] },
      { char: '🎅', keywords: ['santa', 'christmas'] },
      { char: '🤶', keywords: ['mrs claus'] },
      { char: '🦸', keywords: ['superhero'] },
      { char: '🦹', keywords: ['supervillain'] },
      { char: '🧙', keywords: ['wizard', 'mage'] },
      { char: '🧚', keywords: ['fairy'] },
      { char: '🧛', keywords: ['vampire'] },
      { char: '🧜', keywords: ['mermaid'] },
      { char: '🧝', keywords: ['elf'] },
      { char: '🧞', keywords: ['genie'] },
      { char: '🧟', keywords: ['zombie'] },
      { char: '💆', keywords: ['massage', 'relax'] },
      { char: '💇', keywords: ['haircut'] },
      { char: '🚶', keywords: ['walking'] },
      { char: '🧍', keywords: ['standing'] },
      { char: '🧎', keywords: ['kneeling'] },
      { char: '🏃', keywords: ['running'] },
      { char: '💃', keywords: ['dancer', 'dance'] },
      { char: '🕺', keywords: ['dancing man'] },
      { char: '👯', keywords: ['bunny ears', 'party'] },
      { char: '🧖', keywords: ['sauna', 'steam'] },
      { char: '🧗', keywords: ['climbing'] },
      { char: '🤺', keywords: ['fencing'] },
      { char: '🏇', keywords: ['horse racing'] },
      { char: '⛷️', keywords: ['skiing'] },
      { char: '🏂', keywords: ['snowboarding'] },
      { char: '🏌️', keywords: ['golf'] },
      { char: '🏄', keywords: ['surfing'] },
      { char: '🚣', keywords: ['rowing'] },
      { char: '🏊', keywords: ['swimming'] },
      { char: '🏋️', keywords: ['weight lifting', 'gym'] },
      { char: '🚴', keywords: ['cycling', 'bike'] },
      { char: '🤸', keywords: ['cartwheel'] },
      { char: '🤼', keywords: ['wrestling'] },
      { char: '🤽', keywords: ['water polo'] },
      { char: '🤾', keywords: ['handball'] },
      { char: '🧘', keywords: ['yoga', 'meditate', 'calm'] },
      { char: '🛀', keywords: ['bath'] },
      { char: '🛌', keywords: ['sleeping bed'] },
      { char: '👭', keywords: ['women holding hands'] },
      { char: '👫', keywords: ['couple holding hands'] },
      { char: '👬', keywords: ['men holding hands'] },
      { char: '💏', keywords: ['kiss couple'] },
      { char: '💑', keywords: ['couple heart'] },
      { char: '👪', keywords: ['family'] },
    ],
  },
  {
    id: 'animals',
    label: 'Animals & Nature',
    icon: '🐶',
    emojis: [
      { char: '🐶', keywords: ['dog', 'puppy', 'chó'] },
      { char: '🐱', keywords: ['cat', 'kitten', 'mèo'] },
      { char: '🐭', keywords: ['mouse'] },
      { char: '🐹', keywords: ['hamster'] },
      { char: '🐰', keywords: ['rabbit', 'bunny'] },
      { char: '🦊', keywords: ['fox'] },
      { char: '🐻', keywords: ['bear'] },
      { char: '🐼', keywords: ['panda'] },
      { char: '🐻‍❄️', keywords: ['polar bear'] },
      { char: '🐨', keywords: ['koala'] },
      { char: '🐯', keywords: ['tiger'] },
      { char: '🦁', keywords: ['lion'] },
      { char: '🐮', keywords: ['cow'] },
      { char: '🐷', keywords: ['pig'] },
      { char: '🐽', keywords: ['pig nose'] },
      { char: '🐸', keywords: ['frog'] },
      { char: '🐵', keywords: ['monkey'] },
      { char: '🙈', keywords: ['see no evil'] },
      { char: '🙉', keywords: ['hear no evil'] },
      { char: '🙊', keywords: ['speak no evil'] },
      { char: '🐒', keywords: ['monkey'] },
      { char: '🐔', keywords: ['chicken'] },
      { char: '🐧', keywords: ['penguin'] },
      { char: '🐦', keywords: ['bird'] },
      { char: '🐤', keywords: ['chick'] },
      { char: '🐣', keywords: ['hatching chick'] },
      { char: '🦆', keywords: ['duck'] },
      { char: '🦅', keywords: ['eagle'] },
      { char: '🦉', keywords: ['owl'] },
      { char: '🦇', keywords: ['bat'] },
      { char: '🐺', keywords: ['wolf'] },
      { char: '🐗', keywords: ['boar'] },
      { char: '🐴', keywords: ['horse'] },
      { char: '🦄', keywords: ['unicorn'] },
      { char: '🐝', keywords: ['bee'] },
      { char: '🪲', keywords: ['beetle'] },
      { char: '🦋', keywords: ['butterfly'] },
      { char: '🐌', keywords: ['snail'] },
      { char: '🐞', keywords: ['ladybug'] },
      { char: '🐜', keywords: ['ant'] },
      { char: '🕷️', keywords: ['spider'] },
      { char: '🦂', keywords: ['scorpion'] },
      { char: '🐢', keywords: ['turtle'] },
      { char: '🐍', keywords: ['snake'] },
      { char: '🦎', keywords: ['lizard'] },
      { char: '🦖', keywords: ['t-rex', 'dinosaur'] },
      { char: '🦕', keywords: ['dinosaur'] },
      { char: '🐙', keywords: ['octopus'] },
      { char: '🦑', keywords: ['squid'] },
      { char: '🦐', keywords: ['shrimp'] },
      { char: '🦀', keywords: ['crab'] },
      { char: '🐡', keywords: ['pufferfish'] },
      { char: '🐠', keywords: ['fish', 'tropical'] },
      { char: '🐟', keywords: ['fish'] },
      { char: '🐬', keywords: ['dolphin'] },
      { char: '🐳', keywords: ['whale'] },
      { char: '🐋', keywords: ['whale'] },
      { char: '🦈', keywords: ['shark'] },
      { char: '🐊', keywords: ['crocodile'] },
      { char: '🐅', keywords: ['tiger'] },
      { char: '🐆', keywords: ['leopard'] },
      { char: '🦓', keywords: ['zebra'] },
      { char: '🦍', keywords: ['gorilla'] },
      { char: '🦧', keywords: ['orangutan'] },
      { char: '🐘', keywords: ['elephant'] },
      { char: '🦛', keywords: ['hippo'] },
      { char: '🦏', keywords: ['rhino'] },
      { char: '🐪', keywords: ['camel'] },
      { char: '🐫', keywords: ['bactrian camel'] },
      { char: '🦒', keywords: ['giraffe'] },
      { char: '🦘', keywords: ['kangaroo'] },
      { char: '🐃', keywords: ['buffalo'] },
      { char: '🐄', keywords: ['cow'] },
      { char: '🐎', keywords: ['racehorse'] },
      { char: '🐖', keywords: ['pig'] },
      { char: '🐏', keywords: ['ram', 'sheep'] },
      { char: '🐑', keywords: ['sheep'] },
      { char: '🦙', keywords: ['llama'] },
      { char: '🐐', keywords: ['goat'] },
      { char: '🦌', keywords: ['deer'] },
      { char: '🐕', keywords: ['dog'] },
      { char: '🐩', keywords: ['poodle'] },
      { char: '🦮', keywords: ['guide dog'] },
      { char: '🐈', keywords: ['cat'] },
      { char: '🐈‍⬛', keywords: ['black cat'] },
      { char: '🐓', keywords: ['rooster'] },
      { char: '🦃', keywords: ['turkey'] },
      { char: '🦚', keywords: ['peacock'] },
      { char: '🦜', keywords: ['parrot'] },
      { char: '🦢', keywords: ['swan'] },
      { char: '🦩', keywords: ['flamingo'] },
      { char: '🐇', keywords: ['rabbit'] },
      { char: '🦝', keywords: ['raccoon'] },
      { char: '🦨', keywords: ['skunk'] },
      { char: '🦡', keywords: ['badger'] },
      { char: '🐁', keywords: ['mouse'] },
      { char: '🐀', keywords: ['rat'] },
      { char: '🐿️', keywords: ['squirrel'] },
      { char: '🦔', keywords: ['hedgehog'] },
      { char: '🐾', keywords: ['paw prints'] },
      { char: '🐉', keywords: ['dragon'] },
      { char: '🐲', keywords: ['dragon face'] },
      { char: '🌵', keywords: ['cactus'] },
      { char: '🎄', keywords: ['christmas tree'] },
      { char: '🌲', keywords: ['tree', 'pine'] },
      { char: '🌳', keywords: ['tree'] },
      { char: '🌴', keywords: ['palm tree'] },
      { char: '🌱', keywords: ['seedling', 'sprout'] },
      { char: '🌿', keywords: ['herb'] },
      { char: '☘️', keywords: ['shamrock', 'lucky'] },
      { char: '🍀', keywords: ['clover', 'lucky', 'four leaf'] },
      { char: '🎍', keywords: ['bamboo'] },
      { char: '🎋', keywords: ['tanabata'] },
      { char: '🍃', keywords: ['leaves', 'wind'] },
      { char: '🍂', keywords: ['fallen leaf', 'autumn'] },
      { char: '🍁', keywords: ['maple leaf', 'autumn'] },
      { char: '🍄', keywords: ['mushroom'] },
      { char: '🐚', keywords: ['shell'] },
      { char: '🪨', keywords: ['rock'] },
      { char: '🌾', keywords: ['rice', 'wheat'] },
      { char: '💐', keywords: ['bouquet', 'flowers'] },
      { char: '🌷', keywords: ['tulip', 'flower'] },
      { char: '🌹', keywords: ['rose', 'flower', 'hoa hồng'] },
      { char: '🥀', keywords: ['wilted flower'] },
      { char: '🌺', keywords: ['hibiscus'] },
      { char: '🌸', keywords: ['cherry blossom', 'flower'] },
      { char: '🌼', keywords: ['daisy', 'flower'] },
      { char: '🌻', keywords: ['sunflower'] },
      { char: '🌞', keywords: ['sun', 'face'] },
      { char: '🌝', keywords: ['moon face'] },
      { char: '🌛', keywords: ['moon'] },
      { char: '🌜', keywords: ['moon'] },
      { char: '🌚', keywords: ['new moon face'] },
      { char: '🌕', keywords: ['full moon'] },
      { char: '🌖', keywords: ['moon'] },
      { char: '🌗', keywords: ['moon'] },
      { char: '🌘', keywords: ['moon'] },
      { char: '🌑', keywords: ['new moon'] },
      { char: '🌒', keywords: ['moon'] },
      { char: '🌓', keywords: ['moon'] },
      { char: '🌔', keywords: ['moon'] },
      { char: '🌙', keywords: ['crescent moon'] },
      { char: '🌎', keywords: ['earth', 'globe'] },
      { char: '🌍', keywords: ['earth', 'globe'] },
      { char: '🌏', keywords: ['earth', 'globe'] },
      { char: '💫', keywords: ['dizzy', 'star'] },
      { char: '⭐', keywords: ['star'] },
      { char: '🌟', keywords: ['glowing star'] },
      { char: '✨', keywords: ['sparkles', 'shine', 'magic'] },
      { char: '⚡', keywords: ['lightning', 'electric', 'zap'] },
      { char: '☄️', keywords: ['comet'] },
      { char: '💥', keywords: ['explosion', 'boom'] },
      { char: '🔥', keywords: ['fire', 'hot', 'lit'] },
      { char: '🌪️', keywords: ['tornado'] },
      { char: '🌈', keywords: ['rainbow'] },
      { char: '☀️', keywords: ['sun', 'sunny'] },
      { char: '🌤️', keywords: ['sun cloud'] },
      { char: '⛅', keywords: ['cloud sun'] },
      { char: '🌥️', keywords: ['cloud'] },
      { char: '☁️', keywords: ['cloud'] },
      { char: '🌦️', keywords: ['rain sun'] },
      { char: '🌧️', keywords: ['rain'] },
      { char: '⛈️', keywords: ['thunderstorm'] },
      { char: '🌩️', keywords: ['lightning cloud'] },
      { char: '❄️', keywords: ['snowflake', 'cold'] },
      { char: '☃️', keywords: ['snowman'] },
      { char: '⛄', keywords: ['snowman'] },
      { char: '💧', keywords: ['droplet', 'water'] },
      { char: '💦', keywords: ['sweat', 'splash'] },
      { char: '🌊', keywords: ['wave', 'ocean'] },
    ],
  },
  {
    id: 'food',
    label: 'Food & Drink',
    icon: '🍔',
    emojis: [
      { char: '🍏', keywords: ['green apple'] },
      { char: '🍎', keywords: ['apple', 'red'] },
      { char: '🍐', keywords: ['pear'] },
      { char: '🍊', keywords: ['orange', 'tangerine'] },
      { char: '🍋', keywords: ['lemon'] },
      { char: '🍌', keywords: ['banana'] },
      { char: '🍉', keywords: ['watermelon'] },
      { char: '🍇', keywords: ['grapes'] },
      { char: '🍓', keywords: ['strawberry'] },
      { char: '🫐', keywords: ['blueberries'] },
      { char: '🍈', keywords: ['melon'] },
      { char: '🍒', keywords: ['cherries'] },
      { char: '🍑', keywords: ['peach'] },
      { char: '🥭', keywords: ['mango', 'xoài'] },
      { char: '🍍', keywords: ['pineapple'] },
      { char: '🥥', keywords: ['coconut'] },
      { char: '🥝', keywords: ['kiwi'] },
      { char: '🍅', keywords: ['tomato'] },
      { char: '🍆', keywords: ['eggplant'] },
      { char: '🥑', keywords: ['avocado'] },
      { char: '🥦', keywords: ['broccoli'] },
      { char: '🥬', keywords: ['leafy green'] },
      { char: '🥒', keywords: ['cucumber'] },
      { char: '🌶️', keywords: ['hot pepper', 'chili', 'spicy'] },
      { char: '🫑', keywords: ['bell pepper'] },
      { char: '🌽', keywords: ['corn'] },
      { char: '🥕', keywords: ['carrot'] },
      { char: '🫒', keywords: ['olive'] },
      { char: '🧄', keywords: ['garlic'] },
      { char: '🧅', keywords: ['onion'] },
      { char: '🥔', keywords: ['potato'] },
      { char: '🍠', keywords: ['sweet potato'] },
      { char: '🥐', keywords: ['croissant'] },
      { char: '🥯', keywords: ['bagel'] },
      { char: '🍞', keywords: ['bread'] },
      { char: '🥖', keywords: ['baguette'] },
      { char: '🥨', keywords: ['pretzel'] },
      { char: '🧀', keywords: ['cheese'] },
      { char: '🥚', keywords: ['egg'] },
      { char: '🍳', keywords: ['fried egg', 'cooking'] },
      { char: '🧈', keywords: ['butter'] },
      { char: '🥞', keywords: ['pancakes'] },
      { char: '🧇', keywords: ['waffle'] },
      { char: '🥓', keywords: ['bacon'] },
      { char: '🥩', keywords: ['meat', 'steak'] },
      { char: '🍗', keywords: ['chicken leg'] },
      { char: '🍖', keywords: ['meat on bone'] },
      { char: '🌭', keywords: ['hot dog'] },
      { char: '🍔', keywords: ['burger', 'hamburger'] },
      { char: '🍟', keywords: ['fries'] },
      { char: '🍕', keywords: ['pizza'] },
      { char: '🫓', keywords: ['flatbread'] },
      { char: '🥪', keywords: ['sandwich'] },
      { char: '🥙', keywords: ['stuffed flatbread'] },
      { char: '🧆', keywords: ['falafel'] },
      { char: '🌮', keywords: ['taco'] },
      { char: '🌯', keywords: ['burrito'] },
      { char: '🫔', keywords: ['tamale'] },
      { char: '🥗', keywords: ['salad'] },
      { char: '🥘', keywords: ['paella', 'stew'] },
      { char: '🫕', keywords: ['fondue'] },
      { char: '🍝', keywords: ['spaghetti', 'pasta', 'mì'] },
      { char: '🍜', keywords: ['ramen', 'noodles', 'mì'] },
      { char: '🍲', keywords: ['stew', 'hot pot'] },
      { char: '🍛', keywords: ['curry rice'] },
      { char: '🍣', keywords: ['sushi'] },
      { char: '🍱', keywords: ['bento box'] },
      { char: '🥟', keywords: ['dumpling'] },
      { char: '🦪', keywords: ['oyster'] },
      { char: '🍤', keywords: ['fried shrimp'] },
      { char: '🍙', keywords: ['rice ball'] },
      { char: '🍚', keywords: ['rice', 'cơm'] },
      { char: '🍘', keywords: ['rice cracker'] },
      { char: '🍥', keywords: ['fish cake'] },
      { char: '🥠', keywords: ['fortune cookie'] },
      { char: '🥮', keywords: ['moon cake'] },
      { char: '🍢', keywords: ['oden', 'skewer'] },
      { char: '🍡', keywords: ['dango'] },
      { char: '🍧', keywords: ['shaved ice'] },
      { char: '🍨', keywords: ['ice cream'] },
      { char: '🍦', keywords: ['soft serve', 'ice cream'] },
      { char: '🥧', keywords: ['pie'] },
      { char: '🧁', keywords: ['cupcake'] },
      { char: '🍰', keywords: ['cake', 'bánh'] },
      { char: '🎂', keywords: ['birthday cake'] },
      { char: '🍮', keywords: ['custard', 'flan'] },
      { char: '🍭', keywords: ['lollipop', 'candy'] },
      { char: '🍬', keywords: ['candy'] },
      { char: '🍫', keywords: ['chocolate'] },
      { char: '🍿', keywords: ['popcorn'] },
      { char: '🍩', keywords: ['donut'] },
      { char: '🍪', keywords: ['cookie'] },
      { char: '🌰', keywords: ['chestnut'] },
      { char: '🥜', keywords: ['peanuts'] },
      { char: '🍯', keywords: ['honey'] },
      { char: '🥛', keywords: ['milk'] },
      { char: '🍼', keywords: ['baby bottle'] },
      { char: '☕', keywords: ['coffee', 'cà phê'] },
      { char: '🫖', keywords: ['teapot'] },
      { char: '🍵', keywords: ['tea', 'trà'] },
      { char: '🧃', keywords: ['juice box'] },
      { char: '🥤', keywords: ['cup', 'soda'] },
      { char: '🧋', keywords: ['bubble tea', 'trà sữa'] },
      { char: '🍶', keywords: ['sake'] },
      { char: '🍺', keywords: ['beer', 'bia'] },
      { char: '🍻', keywords: ['cheers', 'beer'] },
      { char: '🥂', keywords: ['champagne', 'cheers', 'toast'] },
      { char: '🍷', keywords: ['wine'] },
      { char: '🥃', keywords: ['whiskey'] },
      { char: '🍸', keywords: ['cocktail'] },
      { char: '🍹', keywords: ['tropical drink'] },
      { char: '🍾', keywords: ['champagne bottle', 'celebrate'] },
      { char: '🧊', keywords: ['ice'] },
    ],
  },
  {
    id: 'activities',
    label: 'Activities',
    icon: '⚽',
    emojis: [
      { char: '⚽', keywords: ['soccer', 'football', 'bóng đá'] },
      { char: '🏀', keywords: ['basketball'] },
      { char: '🏈', keywords: ['football', 'american'] },
      { char: '⚾', keywords: ['baseball'] },
      { char: '🥎', keywords: ['softball'] },
      { char: '🎾', keywords: ['tennis'] },
      { char: '🏐', keywords: ['volleyball'] },
      { char: '🏉', keywords: ['rugby'] },
      { char: '🎱', keywords: ['billiards', 'pool', '8 ball'] },
      { char: '🪀', keywords: ['yoyo'] },
      { char: '🏓', keywords: ['ping pong', 'table tennis'] },
      { char: '🏸', keywords: ['badminton'] },
      { char: '🏒', keywords: ['hockey'] },
      { char: '🏑', keywords: ['field hockey'] },
      { char: '🥍', keywords: ['lacrosse'] },
      { char: '🏏', keywords: ['cricket'] },
      { char: '🪃', keywords: ['boomerang'] },
      { char: '🥅', keywords: ['goal net'] },
      { char: '⛳', keywords: ['golf hole'] },
      { char: '🪁', keywords: ['kite'] },
      { char: '🏹', keywords: ['bow arrow', 'archery'] },
      { char: '🎣', keywords: ['fishing'] },
      { char: '🤿', keywords: ['diving'] },
      { char: '🥊', keywords: ['boxing'] },
      { char: '🥋', keywords: ['martial arts'] },
      { char: '🎽', keywords: ['running shirt'] },
      { char: '🛹', keywords: ['skateboard'] },
      { char: '🛼', keywords: ['roller skate'] },
      { char: '🛷', keywords: ['sled'] },
      { char: '⛸️', keywords: ['ice skate'] },
      { char: '🥌', keywords: ['curling'] },
      { char: '🎿', keywords: ['ski'] },
      { char: '⛷️', keywords: ['skier'] },
      { char: '🏂', keywords: ['snowboard'] },
      { char: '🪂', keywords: ['parachute'] },
      { char: '🏋️', keywords: ['weightlifting', 'gym'] },
      { char: '🤼', keywords: ['wrestling'] },
      { char: '🤸', keywords: ['gymnastics'] },
      { char: '⛹️', keywords: ['basketball player'] },
      { char: '🤺', keywords: ['fencing'] },
      { char: '🏆', keywords: ['trophy', 'win', 'award'] },
      { char: '🥇', keywords: ['gold medal', 'first place'] },
      { char: '🥈', keywords: ['silver medal', 'second place'] },
      { char: '🥉', keywords: ['bronze medal', 'third place'] },
      { char: '🏅', keywords: ['medal'] },
      { char: '🎖️', keywords: ['military medal'] },
      { char: '🏵️', keywords: ['rosette'] },
      { char: '🎗️', keywords: ['ribbon'] },
      { char: '🎫', keywords: ['ticket'] },
      { char: '🎟️', keywords: ['tickets'] },
      { char: '🎪', keywords: ['circus tent'] },
      { char: '🤹', keywords: ['juggling'] },
      { char: '🎭', keywords: ['theater', 'masks', 'drama'] },
      { char: '🩰', keywords: ['ballet shoes'] },
      { char: '🎨', keywords: ['art', 'palette', 'painting'] },
      { char: '🎬', keywords: ['movie', 'clapper', 'film'] },
      { char: '🎤', keywords: ['microphone', 'sing', 'karaoke'] },
      { char: '🎧', keywords: ['headphones', 'music'] },
      { char: '🎼', keywords: ['musical score'] },
      { char: '🎹', keywords: ['piano'] },
      { char: '🥁', keywords: ['drum'] },
      { char: '🪘', keywords: ['drum'] },
      { char: '🎷', keywords: ['saxophone'] },
      { char: '🎺', keywords: ['trumpet'] },
      { char: '🎸', keywords: ['guitar'] },
      { char: '🪕', keywords: ['banjo'] },
      { char: '🎻', keywords: ['violin'] },
      { char: '🎲', keywords: ['dice', 'game'] },
      { char: '♟️', keywords: ['chess pawn'] },
      { char: '🎯', keywords: ['dart', 'target', 'bullseye'] },
      { char: '🎳', keywords: ['bowling'] },
      { char: '🎮', keywords: ['video game', 'controller', 'chơi game'] },
      { char: '🎰', keywords: ['slot machine'] },
      { char: '🧩', keywords: ['puzzle piece'] },
    ],
  },
  {
    id: 'travel',
    label: 'Travel & Places',
    icon: '✈️',
    emojis: [
      { char: '🚗', keywords: ['car'] },
      { char: '🚕', keywords: ['taxi'] },
      { char: '🚙', keywords: ['suv'] },
      { char: '🚌', keywords: ['bus'] },
      { char: '🚎', keywords: ['trolleybus'] },
      { char: '🏎️', keywords: ['race car'] },
      { char: '🚓', keywords: ['police car'] },
      { char: '🚑', keywords: ['ambulance'] },
      { char: '🚒', keywords: ['fire truck'] },
      { char: '🚐', keywords: ['van'] },
      { char: '🛻', keywords: ['pickup truck'] },
      { char: '🚚', keywords: ['delivery truck'] },
      { char: '🚛', keywords: ['truck'] },
      { char: '🚜', keywords: ['tractor'] },
      { char: '🏍️', keywords: ['motorcycle'] },
      { char: '🛵', keywords: ['scooter', 'xe máy'] },
      { char: '🚲', keywords: ['bicycle', 'xe đạp'] },
      { char: '🛴', keywords: ['kick scooter'] },
      { char: '🛺', keywords: ['auto rickshaw'] },
      { char: '🚨', keywords: ['siren', 'police light'] },
      { char: '🚔', keywords: ['police car light'] },
      { char: '🚍', keywords: ['bus stop'] },
      { char: '🚘', keywords: ['car'] },
      { char: '🚖', keywords: ['taxi'] },
      { char: '🚡', keywords: ['aerial tramway'] },
      { char: '🚠', keywords: ['gondola'] },
      { char: '🚟', keywords: ['suspension railway'] },
      { char: '🚃', keywords: ['train car'] },
      { char: '🚋', keywords: ['tram car'] },
      { char: '🚞', keywords: ['mountain railway'] },
      { char: '🚝', keywords: ['monorail'] },
      { char: '🚄', keywords: ['bullet train'] },
      { char: '🚅', keywords: ['bullet train'] },
      { char: '🚈', keywords: ['light rail'] },
      { char: '🚂', keywords: ['train', 'steam locomotive'] },
      { char: '🚆', keywords: ['train'] },
      { char: '🚇', keywords: ['metro', 'subway'] },
      { char: '🚊', keywords: ['tram'] },
      { char: '🚉', keywords: ['station'] },
      { char: '✈️', keywords: ['airplane', 'flight', 'máy bay'] },
      { char: '🛫', keywords: ['departure'] },
      { char: '🛬', keywords: ['arrival'] },
      { char: '🛩️', keywords: ['small airplane'] },
      { char: '💺', keywords: ['seat'] },
      { char: '🛰️', keywords: ['satellite'] },
      { char: '🚀', keywords: ['rocket', 'launch', 'space'] },
      { char: '🛸', keywords: ['ufo'] },
      { char: '🚁', keywords: ['helicopter'] },
      { char: '🛶', keywords: ['canoe'] },
      { char: '⛵', keywords: ['sailboat'] },
      { char: '🚤', keywords: ['speedboat'] },
      { char: '🛥️', keywords: ['motorboat'] },
      { char: '🛳️', keywords: ['cruise ship'] },
      { char: '⛴️', keywords: ['ferry'] },
      { char: '🚢', keywords: ['ship'] },
      { char: '⚓', keywords: ['anchor'] },
      { char: '🪝', keywords: ['hook'] },
      { char: '⛽', keywords: ['fuel pump', 'gas'] },
      { char: '🚧', keywords: ['construction', 'barrier'] },
      { char: '🚦', keywords: ['traffic light'] },
      { char: '🚥', keywords: ['traffic light'] },
      { char: '🗺️', keywords: ['map'] },
      { char: '🗿', keywords: ['moai', 'statue'] },
      { char: '🗽', keywords: ['liberty statue'] },
      { char: '🗼', keywords: ['tokyo tower'] },
      { char: '🏰', keywords: ['castle'] },
      { char: '🏯', keywords: ['japanese castle'] },
      { char: '🏟️', keywords: ['stadium'] },
      { char: '🎡', keywords: ['ferris wheel'] },
      { char: '🎢', keywords: ['roller coaster'] },
      { char: '🎠', keywords: ['carousel'] },
      { char: '⛲', keywords: ['fountain'] },
      { char: '⛱️', keywords: ['beach umbrella'] },
      { char: '🏖️', keywords: ['beach', 'biển'] },
      { char: '🏝️', keywords: ['desert island'] },
      { char: '🏜️', keywords: ['desert'] },
      { char: '🌋', keywords: ['volcano'] },
      { char: '⛰️', keywords: ['mountain', 'núi'] },
      { char: '🏔️', keywords: ['snow mountain'] },
      { char: '🗻', keywords: ['mount fuji'] },
      { char: '🏕️', keywords: ['camping'] },
      { char: '⛺', keywords: ['tent'] },
      { char: '🏠', keywords: ['house', 'home', 'nhà'] },
      { char: '🏡', keywords: ['house garden'] },
      { char: '🏘️', keywords: ['houses'] },
      { char: '🏚️', keywords: ['derelict house'] },
      { char: '🏗️', keywords: ['building construction'] },
      { char: '🏭', keywords: ['factory'] },
      { char: '🏢', keywords: ['office building'] },
      { char: '🏬', keywords: ['department store'] },
      { char: '🏣', keywords: ['post office'] },
      { char: '🏤', keywords: ['post office'] },
      { char: '🏥', keywords: ['hospital', 'bệnh viện'] },
      { char: '🏦', keywords: ['bank'] },
      { char: '🏨', keywords: ['hotel'] },
      { char: '🏪', keywords: ['convenience store'] },
      { char: '🏫', keywords: ['school', 'trường học'] },
      { char: '🏩', keywords: ['love hotel'] },
      { char: '💒', keywords: ['wedding'] },
      { char: '🏛️', keywords: ['classical building'] },
      { char: '⛪', keywords: ['church'] },
      { char: '🕌', keywords: ['mosque'] },
      { char: '🛕', keywords: ['hindu temple'] },
      { char: '🕍', keywords: ['synagogue'] },
      { char: '🕋', keywords: ['kaaba'] },
      { char: '🌁', keywords: ['foggy city'] },
      { char: '🌃', keywords: ['night city', 'stars'] },
      { char: '🏙️', keywords: ['cityscape'] },
      { char: '🌄', keywords: ['sunrise mountain'] },
      { char: '🌅', keywords: ['sunrise'] },
      { char: '🌆', keywords: ['sunset city'] },
      { char: '🌇', keywords: ['sunset'] },
      { char: '🌉', keywords: ['bridge night'] },
      { char: '♨️', keywords: ['hot springs'] },
      { char: '🎇', keywords: ['sparkler'] },
      { char: '🎆', keywords: ['fireworks'] },
    ],
  },
  {
    id: 'objects',
    label: 'Objects',
    icon: '💡',
    emojis: [
      { char: '⌚', keywords: ['watch'] },
      { char: '📱', keywords: ['phone', 'mobile', 'điện thoại'] },
      { char: '💻', keywords: ['laptop', 'computer', 'máy tính'] },
      { char: '⌨️', keywords: ['keyboard'] },
      { char: '🖥️', keywords: ['desktop computer'] },
      { char: '🖨️', keywords: ['printer'] },
      { char: '🖱️', keywords: ['mouse'] },
      { char: '💽', keywords: ['minidisc'] },
      { char: '💾', keywords: ['floppy disk', 'save'] },
      { char: '💿', keywords: ['cd'] },
      { char: '📀', keywords: ['dvd'] },
      { char: '📷', keywords: ['camera', 'photo'] },
      { char: '📸', keywords: ['camera flash'] },
      { char: '📹', keywords: ['video camera'] },
      { char: '🎥', keywords: ['movie camera'] },
      { char: '📞', keywords: ['telephone', 'call'] },
      { char: '☎️', keywords: ['phone'] },
      { char: '📟', keywords: ['pager'] },
      { char: '📠', keywords: ['fax'] },
      { char: '📺', keywords: ['tv', 'television'] },
      { char: '📻', keywords: ['radio'] },
      { char: '🎙️', keywords: ['studio microphone'] },
      { char: '🔋', keywords: ['battery'] },
      { char: '🪫', keywords: ['low battery'] },
      { char: '🔌', keywords: ['plug', 'charger'] },
      { char: '💡', keywords: ['bulb', 'idea', 'light'] },
      { char: '🔦', keywords: ['flashlight'] },
      { char: '🕯️', keywords: ['candle'] },
      { char: '🪔', keywords: ['diya lamp'] },
      { char: '📔', keywords: ['notebook'] },
      { char: '📕', keywords: ['closed book'] },
      { char: '📖', keywords: ['open book', 'read'] },
      { char: '📗', keywords: ['green book'] },
      { char: '📘', keywords: ['blue book'] },
      { char: '📙', keywords: ['orange book'] },
      { char: '📚', keywords: ['books', 'study'] },
      { char: '📓', keywords: ['notebook'] },
      { char: '📒', keywords: ['ledger'] },
      { char: '📃', keywords: ['page'] },
      { char: '📜', keywords: ['scroll'] },
      { char: '📄', keywords: ['document', 'page'] },
      { char: '📰', keywords: ['newspaper'] },
      { char: '🗞️', keywords: ['rolled newspaper'] },
      { char: '📑', keywords: ['bookmark tabs'] },
      { char: '🔖', keywords: ['bookmark'] },
      { char: '🏷️', keywords: ['label', 'tag'] },
      { char: '💰', keywords: ['money bag', 'tiền'] },
      { char: '🪙', keywords: ['coin'] },
      { char: '💴', keywords: ['yen'] },
      { char: '💵', keywords: ['dollar'] },
      { char: '💶', keywords: ['euro'] },
      { char: '💷', keywords: ['pound'] },
      { char: '💸', keywords: ['money flying', 'spend'] },
      { char: '💳', keywords: ['credit card'] },
      { char: '🧾', keywords: ['receipt'] },
      { char: '💹', keywords: ['chart increasing yen'] },
      { char: '✉️', keywords: ['envelope', 'mail'] },
      { char: '📧', keywords: ['email'] },
      { char: '📨', keywords: ['incoming mail'] },
      { char: '📩', keywords: ['envelope arrow'] },
      { char: '📤', keywords: ['outbox'] },
      { char: '📥', keywords: ['inbox'] },
      { char: '📦', keywords: ['package', 'box'] },
      { char: '📫', keywords: ['mailbox'] },
      { char: '📪', keywords: ['mailbox closed'] },
      { char: '📬', keywords: ['mailbox open'] },
      { char: '📭', keywords: ['mailbox empty'] },
      { char: '📮', keywords: ['postbox'] },
      { char: '🗳️', keywords: ['ballot box'] },
      { char: '✏️', keywords: ['pencil'] },
      { char: '✒️', keywords: ['pen'] },
      { char: '🖋️', keywords: ['fountain pen'] },
      { char: '🖊️', keywords: ['pen'] },
      { char: '🖌️', keywords: ['paintbrush'] },
      { char: '🖍️', keywords: ['crayon'] },
      { char: '📝', keywords: ['memo', 'note'] },
      { char: '💼', keywords: ['briefcase', 'work'] },
      { char: '📁', keywords: ['folder'] },
      { char: '📂', keywords: ['open folder'] },
      { char: '🗂️', keywords: ['card index'] },
      { char: '📅', keywords: ['calendar', 'date'] },
      { char: '📆', keywords: ['calendar'] },
      { char: '🗒️', keywords: ['notepad'] },
      { char: '🗓️', keywords: ['calendar spiral'] },
      { char: '📇', keywords: ['card index'] },
      { char: '📈', keywords: ['chart increasing'] },
      { char: '📉', keywords: ['chart decreasing'] },
      { char: '📊', keywords: ['bar chart'] },
      { char: '📋', keywords: ['clipboard'] },
      { char: '📌', keywords: ['pushpin', 'pin'] },
      { char: '📍', keywords: ['round pushpin', 'location'] },
      { char: '📎', keywords: ['paperclip'] },
      { char: '🖇️', keywords: ['linked paperclips'] },
      { char: '📏', keywords: ['ruler'] },
      { char: '📐', keywords: ['triangular ruler'] },
      { char: '✂️', keywords: ['scissors', 'cut'] },
      { char: '🗃️', keywords: ['card file box'] },
      { char: '🗄️', keywords: ['file cabinet'] },
      { char: '🗑️', keywords: ['wastebasket', 'trash', 'delete'] },
      { char: '🔒', keywords: ['locked'] },
      { char: '🔓', keywords: ['unlocked'] },
      { char: '🔏', keywords: ['locked pen'] },
      { char: '🔐', keywords: ['locked key'] },
      { char: '🔑', keywords: ['key'] },
      { char: '🗝️', keywords: ['old key'] },
      { char: '🔨', keywords: ['hammer'] },
      { char: '🪓', keywords: ['axe'] },
      { char: '⛏️', keywords: ['pick'] },
      { char: '🔧', keywords: ['wrench', 'tool'] },
      { char: '🔩', keywords: ['nut bolt'] },
      { char: '⚙️', keywords: ['gear', 'settings'] },
      { char: '🗜️', keywords: ['clamp'] },
      { char: '⚖️', keywords: ['balance scale'] },
      { char: '🔗', keywords: ['link', 'chain'] },
      { char: '⛓️', keywords: ['chains'] },
      { char: '🧰', keywords: ['toolbox'] },
      { char: '🧲', keywords: ['magnet'] },
      { char: '🔫', keywords: ['gun'] },
      { char: '💣', keywords: ['bomb'] },
      { char: '🧨', keywords: ['firecracker'] },
      { char: '🪃', keywords: ['boomerang'] },
      { char: '🔮', keywords: ['crystal ball'] },
      { char: '🧿', keywords: ['nazar amulet'] },
      { char: '🎁', keywords: ['gift', 'present', 'quà'] },
      { char: '🎀', keywords: ['ribbon', 'bow'] },
      { char: '🪄', keywords: ['magic wand'] },
    ],
  },
  {
    id: 'symbols',
    label: 'Symbols',
    icon: '❤️',
    emojis: [
      { char: '❤️', keywords: ['red heart', 'love', 'yêu'] },
      { char: '🧡', keywords: ['orange heart'] },
      { char: '💛', keywords: ['yellow heart'] },
      { char: '💚', keywords: ['green heart'] },
      { char: '💙', keywords: ['blue heart'] },
      { char: '💜', keywords: ['purple heart'] },
      { char: '🖤', keywords: ['black heart'] },
      { char: '🤍', keywords: ['white heart'] },
      { char: '🤎', keywords: ['brown heart'] },
      { char: '💔', keywords: ['broken heart', 'sad'] },
      { char: '❤️‍🔥', keywords: ['heart on fire'] },
      { char: '❤️‍🩹', keywords: ['mending heart'] },
      { char: '💕', keywords: ['two hearts', 'love'] },
      { char: '💞', keywords: ['revolving hearts'] },
      { char: '💓', keywords: ['beating heart'] },
      { char: '💗', keywords: ['growing heart'] },
      { char: '💖', keywords: ['sparkling heart'] },
      { char: '💘', keywords: ['heart arrow', 'cupid'] },
      { char: '💝', keywords: ['heart ribbon', 'gift'] },
      { char: '💟', keywords: ['heart decoration'] },
      { char: '☮️', keywords: ['peace symbol'] },
      { char: '✝️', keywords: ['cross'] },
      { char: '☪️', keywords: ['star crescent'] },
      { char: '🕉️', keywords: ['om'] },
      { char: '☸️', keywords: ['wheel dharma'] },
      { char: '✡️', keywords: ['star of david'] },
      { char: '🔯', keywords: ['six pointed star'] },
      { char: '🕎', keywords: ['menorah'] },
      { char: '☯️', keywords: ['yin yang'] },
      { char: '☦️', keywords: ['orthodox cross'] },
      { char: '🛐', keywords: ['worship'] },
      { char: '⛎', keywords: ['ophiuchus'] },
      { char: '♈', keywords: ['aries'] },
      { char: '♉', keywords: ['taurus'] },
      { char: '♊', keywords: ['gemini'] },
      { char: '♋', keywords: ['cancer'] },
      { char: '♌', keywords: ['leo'] },
      { char: '♍', keywords: ['virgo'] },
      { char: '♎', keywords: ['libra'] },
      { char: '♏', keywords: ['scorpio'] },
      { char: '♐', keywords: ['sagittarius'] },
      { char: '♑', keywords: ['capricorn'] },
      { char: '♒', keywords: ['aquarius'] },
      { char: '♓', keywords: ['pisces'] },
      { char: '🆔', keywords: ['id'] },
      { char: '⚛️', keywords: ['atom'] },
      { char: '🉑', keywords: ['accept'] },
      { char: '☢️', keywords: ['radioactive'] },
      { char: '☣️', keywords: ['biohazard'] },
      { char: '📴', keywords: ['phone off'] },
      { char: '📳', keywords: ['vibration mode'] },
      { char: '🈶', keywords: ['not free'] },
      { char: '🈚', keywords: ['free'] },
      { char: '🈸', keywords: ['application'] },
      { char: '🈺', keywords: ['open for business'] },
      { char: '🈷️', keywords: ['monthly amount'] },
      { char: '✴️', keywords: ['sparkle'] },
      { char: '🆚', keywords: ['vs'] },
      { char: '💮', keywords: ['white flower'] },
      { char: '🉐', keywords: ['bargain'] },
      { char: '㊙️', keywords: ['secret'] },
      { char: '㊗️', keywords: ['congratulations'] },
      { char: '🈴', keywords: ['passing grade'] },
      { char: '🈵', keywords: ['no vacancy'] },
      { char: '🈹', keywords: ['discount'] },
      { char: '🈲', keywords: ['prohibited'] },
      { char: '🅰️', keywords: ['a button'] },
      { char: '🅱️', keywords: ['b button'] },
      { char: '🆎', keywords: ['ab button'] },
      { char: '🆑', keywords: ['cl button'] },
      { char: '🅾️', keywords: ['o button'] },
      { char: '🆘', keywords: ['sos', 'help'] },
      { char: '❌', keywords: ['cross mark', 'no', 'wrong'] },
      { char: '⭕', keywords: ['circle', 'correct'] },
      { char: '🛑', keywords: ['stop sign'] },
      { char: '⛔', keywords: ['no entry'] },
      { char: '📛', keywords: ['name badge'] },
      { char: '🚫', keywords: ['prohibited', 'no'] },
      { char: '💯', keywords: ['hundred', 'perfect', '100'] },
      { char: '💢', keywords: ['anger symbol'] },
      { char: '♨️', keywords: ['hot springs'] },
      { char: '🚷', keywords: ['no pedestrians'] },
      { char: '🚯', keywords: ['no littering'] },
      { char: '🚳', keywords: ['no bicycles'] },
      { char: '🚱', keywords: ['non-potable water'] },
      { char: '🔞', keywords: ['18+', 'no minors'] },
      { char: '📵', keywords: ['no phones'] },
      { char: '❗', keywords: ['exclamation', 'warning'] },
      { char: '❕', keywords: ['exclamation'] },
      { char: '❓', keywords: ['question mark'] },
      { char: '❔', keywords: ['question'] },
      { char: '‼️', keywords: ['double exclamation'] },
      { char: '⁉️', keywords: ['exclamation question'] },
      { char: '🔅', keywords: ['dim'] },
      { char: '🔆', keywords: ['bright'] },
      { char: '〽️', keywords: ['part alternation'] },
      { char: '⚠️', keywords: ['warning'] },
      { char: '🚸', keywords: ['children crossing'] },
      { char: '🔱', keywords: ['trident'] },
      { char: '⚜️', keywords: ['fleur-de-lis'] },
      { char: '🔰', keywords: ['beginner'] },
      { char: '♻️', keywords: ['recycle'] },
      { char: '✅', keywords: ['check mark', 'done', 'yes'] },
      { char: '🈯', keywords: ['reserved'] },
      { char: '💹', keywords: ['chart yen'] },
      { char: '❇️', keywords: ['sparkle'] },
      { char: '✳️', keywords: ['asterisk'] },
      { char: '❎', keywords: ['cross mark button'] },
      { char: '🌐', keywords: ['globe', 'internet'] },
      { char: '💠', keywords: ['diamond dot'] },
      { char: 'Ⓜ️', keywords: ['m circle'] },
      { char: '🌀', keywords: ['cyclone', 'swirl'] },
      { char: '💤', keywords: ['zzz', 'sleep'] },
      { char: '🏧', keywords: ['atm'] },
      { char: '🚾', keywords: ['water closet'] },
      { char: '♿', keywords: ['wheelchair'] },
      { char: '🅿️', keywords: ['parking'] },
      { char: '🈳', keywords: ['vacancy'] },
      { char: '🈂️', keywords: ['service charge'] },
      { char: '🛂', keywords: ['passport control'] },
      { char: '🛃', keywords: ['customs'] },
      { char: '🛄', keywords: ['baggage claim'] },
      { char: '🛅', keywords: ['left luggage'] },
      { char: '✔️', keywords: ['check mark'] },
      { char: '☑️', keywords: ['checkbox'] },
      { char: '🔘', keywords: ['radio button'] },
      { char: '🔴', keywords: ['red circle'] },
      { char: '🟠', keywords: ['orange circle'] },
      { char: '🟡', keywords: ['yellow circle'] },
      { char: '🟢', keywords: ['green circle', 'online'] },
      { char: '🔵', keywords: ['blue circle'] },
      { char: '🟣', keywords: ['purple circle'] },
      { char: '⚫', keywords: ['black circle'] },
      { char: '⚪', keywords: ['white circle'] },
      { char: '🟤', keywords: ['brown circle'] },
    ],
  },
  {
    id: 'flags',
    label: 'Flags',
    icon: '🏁',
    emojis: [
      { char: '🏁', keywords: ['checkered flag', 'finish'] },
      { char: '🚩', keywords: ['triangular flag'] },
      { char: '🎌', keywords: ['crossed flags'] },
      { char: '🏴', keywords: ['black flag'] },
      { char: '🏳️', keywords: ['white flag', 'surrender'] },
      { char: '🏳️‍🌈', keywords: ['rainbow flag', 'pride'] },
      { char: '🏳️‍⚧️', keywords: ['transgender flag'] },
      { char: '🏴‍☠️', keywords: ['pirate flag'] },
      { char: '🇻🇳', keywords: ['vietnam', 'việt nam'] },
      { char: '🇺🇸', keywords: ['united states', 'usa'] },
      { char: '🇬🇧', keywords: ['united kingdom', 'uk'] },
      { char: '🇯🇵', keywords: ['japan'] },
      { char: '🇰🇷', keywords: ['korea'] },
      { char: '🇨🇳', keywords: ['china'] },
      { char: '🇫🇷', keywords: ['france'] },
      { char: '🇩🇪', keywords: ['germany'] },
      { char: '🇮🇹', keywords: ['italy'] },
      { char: '🇪🇸', keywords: ['spain'] },
      { char: '🇷🇺', keywords: ['russia'] },
      { char: '🇮🇳', keywords: ['india'] },
      { char: '🇧🇷', keywords: ['brazil'] },
      { char: '🇨🇦', keywords: ['canada'] },
      { char: '🇦🇺', keywords: ['australia'] },
      { char: '🇸🇬', keywords: ['singapore'] },
      { char: '🇹🇭', keywords: ['thailand'] },
      { char: '🇮🇩', keywords: ['indonesia'] },
      { char: '🇵🇭', keywords: ['philippines'] },
      { char: '🇲🇾', keywords: ['malaysia'] },
    ],
  },
];
