// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Migrations must run over a DIRECT/session connection, NOT the pgbouncer
    // transaction pooler (port 6543) the app runtime uses — transaction mode
    // doesn't support the advisory locks `migrate deploy` takes, so it hangs
    // there. DIRECT_URL points at the session pooler (port 5432); it falls back
    // to DATABASE_URL for local setups that don't set it.
    url: process.env["DIRECT_URL"] || process.env["DATABASE_URL"],
  },
});
