// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // CLI-only (migrate/generate/studio): needs the session-mode connection,
    // not the transaction pooler the running app uses. See backend/.env.
    url: process.env["DIRECT_URL"] ?? process.env["DATABASE_URL"],
  },
});
